export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';

export const SIGNIN_REQUEST = 'SIGNIN_REQUEST';
export const SIGNIN_FAIL = 'SIGNIN_FAIL';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';

export const REQUEST_REQUEST = 'REQUEST_REQUEST';
export const REQUEST_FAIL = 'REQUEST_FAIL';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGOUT = 'LOGOUT';

export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';

export const CONFIRM_OTP_REQUEST = 'CONFIRM_OTP_REQUEST';
export const CONFIRM_OTP_FAIL = 'CONFIRM_OTP_FAIL';
export const CONFIRM_OTP_SUCCESS = 'CONFIRM_OTP_SUCCESS';

export const SET_PASSWORD_REQUEST = 'SET_PASSWORD_REQUEST';
export const SET_PASSWORD_FAIL = 'SET_PASSWORD_FAIL';
export const SET_PASSWORD_SUCCESS = 'SET_PASSWORD_SUCCESS';

export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST';
export const GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';

export const GET_SUBCATEGORIES_REQUEST = 'GET_SUBCATEGORIES_REQUEST';
export const GET_SUBCATEGORIES_FAIL = 'GET_SUBCATEGORIES_FAIL';
export const GET_SUBCATEGORIES_SUCCESS = 'GET_SUBCATEGORIES_SUCCESS';

export const GET_ALL_CATEGORIES_REQUEST = 'GET_ALL_CATEGORIES_REQUEST';
export const GET_ALL_CATEGORIES_FAIL = 'GET_ALL_CATEGORIES_FAIL';
export const GET_ALL_CATEGORIES_SUCCESS = 'GET_ALL_CATEGORIES_SUCCESS';
export const GET_ALL_CATEGORIES_APPEND_SUCCESS =
  'GET_ALL_CATEGORIES_APPEND_SUCCESS';

export const GET_FEATURED_REQUEST = 'GET_FEATURED_REQUEST';
export const GET_FEATURED_FAIL = 'GET_FEATURED_FAIL';
export const GET_FEATURED_SUCCESS = 'GET_FEATURED_SUCCESS';
export const GET_FEATURED_APPEND_SUCCESS = 'GET_FEATURED_APPEND_SUCCESS';

export const GET_LASTORDER_REQUEST = 'GET_LASTORDER_REQUEST';
export const GET_LASTORDER_FAIL = 'GET_LASTORDER_FAIL';
export const GET_LASTORDER_SUCCESS = 'GET_LASTORDER_SUCCESS';
export const GET_LASTORDER_APPEND_SUCCESS = 'GET_LASTORDER_APPEND_SUCCESS';

export const GET_ACTIVE_LASTORDER_REQUEST = 'GET_ACTIVE_LASTORDER_REQUEST';
export const GET_ACTIVE_LASTORDER_FAIL = 'GET_ACTIVE_LASTORDER_FAIL';
export const GET_ACTIVE_LASTORDER_SUCCESS = 'GET_ACTIVE_LASTORDER_SUCCESS';
export const GET_ACTIVE_LASTORDER_APPEND_SUCCESS =
  'GET_ACTIVE_LASTORDER_APPEND_SUCCESS';

export const GET_FAVOURITE_REQUEST = 'GET_FAVOURITE_REQUEST';
export const GET_FAVOURITE_FAIL = 'GET_FAVOURITE_FAIL';
export const GET_FAVOURITE_SUCCESS = 'GET_FAVOURITE_SUCCESS';
export const GET_FAVOURITE_APPEND_SUCCESS = 'GET_FAVOURITE_APPEND_SUCCESS';

export const GET_SPECIFIC_FAVOURITE_REQUEST = 'GET_SPECIFIC_FAVOURITE_REQUEST';
export const GET_SPECIFIC_FAVOURITE_FAIL = 'GET_SPECIFIC_FAVOURITE_FAIL';
export const GET_SPECIFIC_FAVOURITE_SUCCESS = 'GET_SPECIFIC_FAVOURITE_SUCCESS';
export const GET_SPECIFIC_FAVOURITE_APPEND_SUCCESS =
  'GET_SPECIFIC_FAVOURITE_APPEND_SUCCESS';

export const NOTIFICATION_DETAILS = 'NOTIFICATION_DETAILS';

export const GET_SPECIFIC_FEATURED_REQUEST = 'GET_SPECIFIC_FEATURED_REQUEST';
export const GET_SPECIFIC_FEATURED_FAIL = 'GET_SPECIFIC_FEATURED_FAIL';
export const GET_SPECIFIC_FEATURED_SUCCESS = 'GET_SPECIFIC_FEATURED_SUCCESS';
export const GET_FEATURED_SPECIFIC_APPEND_SUCCESS =
  'GET_FEATURED_SPECIFIC_APPEND_SUCCESS';

export const GET_MERCHANT_ITEMS_REQUEST = 'GET_MERCHANT_ITEMS_REQUEST';
export const GET_MERCHANT_ITEMS_FAIL = 'GET_MERCHANT_ITEMS_FAIL';
export const GET_MERCHANT_ITEMS_SUCCESS = 'GET_MERCHANT_ITEMS_SUCCESS';

export const LIKE_REQUEST = 'LIKE_REQUEST';
export const LIKE_FAIL = 'LIKE_FAIL';
export const LIKE_SUCCESS = 'LIKE_SUCCESS';

export const GET_BANNERS_REQUEST = 'GET_BANNERS_REQUEST';
export const GET_BANNERS_FAIL = 'GET_BANNERS_FAIL';
export const GET_BANNERS_SUCCESS = 'GET_BANNERS_SUCCESS';

export const GET_MERCHANT_BANNERS_REQUEST = 'GET_MERCHANT_BANNERS_REQUEST';
export const GET_MERCHANT_BANNERS_FAIL = 'GET_MERCHANT_BANNERS_FAIL';
export const GET_MERCHANT_BANNERS_SUCCESS = 'GET_MERCHANT_BANNERS_SUCCESS';

export const GET_MERCHANT_LISTING_REQUEST = 'GET_MERCHANT_LISTING_REQUEST';
export const GET_MERCHANT_LISTING_FAIL = 'GET_MERCHANT_LISTING_FAIL';
export const GET_MERCHANT_LISTING_SUCCESS = 'GET_MERCHANT_LISTING_SUCCESS';

export const GET_MERCHANT_APPEND_LISTING_SUCCESS =
  'GET_MERCHANT_APPEND_LISTING_SUCCESS';

export const ADD_CART_REQUEST = 'ADD_CART_REQUEST';
export const ADD_CART_FAIL = 'ADD_CART_FAIL';
export const ADD_CART_SUCCESS = 'ADD_CART_SUCCESS';

export const GET_CART_REQUEST = 'GET_CART_REQUEST';
export const GET_CART_FAIL = 'GET_CART_FAIL';
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS';

export const DROP_LOCATIONS = 'DROP_LOCATIONS';

export const ADD_NEW_ADDRESS_REQUEST = 'ADD_NEW_ADDRESS_REQUEST';
export const ADD_NEW_ADDRESS_FAIL = 'ADD_NEW_ADDRESS_FAIL';
export const ADD_NEW_ADDRESS_SUCCESS = 'ADD_NEW_ADDRESS_SUCCESS';

export const GET_ADDRESS_REQUEST = 'GET_ADDRESS_REQUEST';
export const GET_ADDRESS_FAIL = 'GET_ADDRESS_FAIL';
export const GET_ADDRESS_SUCCESS = 'GET_ADDRESS_SUCCESS';

export const UPDATE_ADDRESS_REQUEST = 'UPDATE_ADDRESS_REQUEST';
export const UPDATE_ADDRESS_FAIL = 'UPDATE_ADDRESS_FAIL';
export const UPDATE_ADDRESS_SUCCESS = 'UPDATE_ADDRESS_SUCCESS';

export const DELETE_ADDRESS_REQUEST = 'DELETE_ADDRESS_REQUEST';
export const DELETE_ADDRESS_FAIL = 'DELETE_ADDRESS_FAIL';
export const DELETE_ADDRESS_SUCCESS = 'DELETE_ADDRESS_SUCCESS';

export const REMOVE_PRODUCT_REQUEST = 'REMOVE_PRODUCT_REQUEST';
export const REMOVE_PRODUCT_FAIL = 'REMOVE_PRODUCT_FAIL';
export const REMOVE_PRODUCT_SUCCESS = 'REMOVE_PRODUCT_SUCCESS';

export const CART_TOTAL = 'CART_TOTAL';

export const UPLOAD_ID_REQUEST = 'UPLOAD_ID_REQUEST';
export const UPLOAD_ID_FAIL = 'UPLOAD_ID_FAIL';
export const UPLOAD_ID_SUCCESS = 'UPLOAD_ID_SUCCESS';

export const SAVE_SIGNATURE = 'SAVE_SIGNATURE';

export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';

export const SAVE_MANUAL_ADDRESS = 'SAVE_MANUAL_ADDRESS';

export const CLEAR_CART_REQUEST = 'CLEAR_CART_REQUEST';
export const CLEAR_CART_FAIL = 'CLEAR_CART_FAIL';
export const CLEAR_CART_SUCCESS = 'CLEAR_CART_SUCCESS';

export const GET_CARD_REQUEST = 'GET_CARD_REQUEST';
export const GET_CARD_FAIL = 'GET_CARD_FAIL';
export const GET_CARD_SUCCESS = 'GET_CARD_SUCCESS';

export const ADD_CARD_REQUEST = 'ADD_CARD_REQUEST';
export const ADD_CARD_FAIL = 'ADD_CARD_FAIL';
export const ADD_CARD_SUCCESS = 'ADD_CARD_SUCCESS';

export const REMOVE_CARD_REQUEST = 'REMOVE_CARD_REQUEST';
export const REMOVE_CARD_FAIL = 'REMOVE_CARD_FAIL';
export const REMOVE_CARD_SUCCESS = 'REMOVE_CARD_SUCCESS';

export const PAYMENT_TYPE = 'PAYMENT_TYPE';
export const SELECTED_CARD = 'SELECTED_CARD';

export const GET_TAX_REQUEST = 'GET_TAX_REQUEST';
export const GET_TAX_FAIL = 'GET_TAX_FAIL';
export const GET_TAX_SUCCESS = 'GET_TAX_SUCCESS';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_FAIL = 'GET_USER_FAIL';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';

export const GET_ADDON_REQUEST = 'GET_ADDON_REQUEST';
export const GET_ADDON_FAIL = 'GET_ADDON_FAIL';
export const GET_ADDON_SUCCESS = 'GET_ADDON_SUCCESS';

export const GET_FAQ_REQUEST = 'GET_FAQ_REQUEST';
export const GET_FAQ_FAIL = 'GET_FAQ_FAIL';
export const GET_FAQ_SUCCESS = 'GET_FAQ_SUCCESS';

export const GET_NOTIFICATION_REQUEST = 'GET_NOTIFICATION_REQUEST';
export const GET_NOTIFICATION_FAIL = 'GET_NOTIFICATION_FAIL';
export const GET_NOTIFICATION_SUCCESS = 'GET_NOTIFICATION_SUCCESS';

export const UPDATE_NOTIFICATION_REQUEST = 'UPDATE_NOTIFICATION_REQUEST';
export const UPDATE_NOTIFICATION_FAIL = 'UPDATE_NOTIFICATION_FAIL';
export const UPDATE_NOTIFICATION_SUCCESS = 'UPDATE_NOTIFICATION_SUCCESS';

export const SOCKET_REGISTER_REQUEST = 'SOCKET_REGISTER_REQUEST';
export const SOCKET_REGISTER_FAIL = 'SOCKET_REGISTER_FAIL';
export const SOCKET_REGISTER_SUCCESS = 'SOCKET_REGISTER_SUCCESS';

export const UPLOAD_CHAT_IMG_REQUEST = 'UPLOAD_CHAT_IMG_REQUEST';
export const UPLOAD_CHAT_IMG_FAIL = 'UPLOAD_CHAT_IMG_FAIL';
export const UPLOAD_CHAT_IMG_SUCCESS = 'UPLOAD_CHAT_IMG_SUCCESS';

export const DELETE_CHAT_REQUEST = 'DELETE_CHAT_REQUEST';
export const DELETE_CHAT_FAIL = 'DELETE_CHAT_FAIL';
export const DELETE_CHAT_SUCCESS = 'DELETE_CHAT_SUCCESS';

export const GET_INBOX_REQUEST = 'GET_INBOX_REQUEST';
export const GET_INBOX_FAIL = 'GET_INBOX_FAIL';
export const GET_INBOX_SUCCESS = 'GET_INBOX_SUCCESS';

export const GET_CHAT_LIST_REQUEST = 'GET_CHAT_LIST_REQUEST';
export const GET_CHAT_LIST_FAIL = 'GET_CHAT_LIST_FAIL';
export const GET_CHAT_LIST_SUCCESS = 'GET_CHAT_LIST_SUCCESS';

export const CREATE_CHAT_ROOM_REQUEST = 'CREATE_CHAT_ROOM_REQUEST';
export const CREATE_CHAT_ROOM_FAIL = 'CREATE_CHAT_ROOM_FAIL';
export const CREATE_CHAT_ROOM_SUCCESS = 'CREATE_CHAT_ROOM_SUCCESS';

export const RATE_USER_REQUEST = 'RATE_USER_REQUEST';
export const RATE_USER_FAIL = 'RATE_USER_FAIL';
export const RATE_USER_SUCCESS = 'RATE_USER_SUCCESS';

export const CHANGE_THEME = 'CHANGE_THEME';

export const CHECK_ZONE_REQUEST = 'CHECK_ZONE_REQUEST';
export const CHECK_ZONE_FAIL = 'CHECK_ZONE_FAIL';
export const CHECK_ZONE_SUCCESS = 'CHECK_ZONE_SUCCESS';

export const FETCH_ZONE_REQUEST = 'FETCH_ZONE_REQUEST';
export const FETCH_ZONE_FAIL = 'FETCH_ZONE_FAIL';
export const FETCH_ZONE_SUCCESS = 'FETCH_ZONE_SUCCESS';

export const GET_TERMS_REQUEST = 'GET_TERMS_REQUEST';
export const GET_TERMS_FAIL = 'GET_TERMS_FAIL';
export const GET_TERMS_SUCCESS = 'GET_TERMS_SUCCESS';

export const COMPLETE_JOB_REQUEST = 'COMPLETE_JOB_REQUEST';
export const COMPLETE_JOB_FAIL = 'COMPLETE_JOB_FAIL';
export const COMPLETE_JOB_SUCCESS = 'COMPLETE_JOB_SUCCESS';

export const ADMIN_ID_REQUEST = 'ADMIN_ID_REQUEST';
export const ADMIN_ID_FAIL = 'ADMIN_ID_FAIL';
export const ADMIN_ID_SUCCESS = 'ADMIN_ID_SUCCESS';

export const DELIVERY_MODAL = 'DELIVERY_MODAL';

export const SELECTED_ORDER = 'SELECTED_ORDER';

export const UPDATE_ORDER_STATUS_REQUEST = 'UPDATE_ORDER_STATUS_REQUEST';
export const UPDATE_ORDER_STATUS_FAIL = 'UPDATE_ORDER_STATUS_FAIL';
export const UPDATE_ORDER_STATUS_SUCCESS = 'UPDATE_ORDER_STATUS_SUCCESS';

export const SELECTED_DETAILS = 'SELECTED_DETAILS';

export const MUTE_CHAT_REQUEST = 'MUTE_CHAT_REQUEST';
export const MUTE_CHAT_FAIL = 'MUTE_CHAT_FAIL';
export const MUTE_CHAT_SUCCESS = 'MUTE_CHAT_SUCCESS';

export const READ_MESSAGE_REQUEST = 'READ_MESSAGE_REQUEST';
export const READ_MESSAGE_FAIL = 'READ_MESSAGE_FAIL';
export const READ_MESSAGE_SUCCESS = 'READ_MESSAGE_SUCCESS';

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
