export default {
  // SERVER_URL: 'https://mean.stagingsdei.com:6047/',
  SERVER_URL: "http://smartfood.live:6104/",

  // IMG_URL: 'https://mean.stagingsdei.com:6047',
  IMG_URL: "http://smartfood.live:6104",
  // SERVER_URL: 'https://536b10defc03.ngrok.io/',
  // IMG_URL: 'https://536b10defc03.ngrok.io/',
  LOGIN: "user/login",
  REGISTER: "user/register",
  FORGOT_PASSWORD: "user/forgot",
  CONFIRM_OTP: "user/verify",
  SET_PASSWORD: "user/reset",
  GET_CATEGORIES: "category/categoriesList?",
  GET_SUBCATEGORIES: "subCategory/getSubCatId?",
  GET_FEATURED: "merchant/getFeaturedListing?",
  GET_FAVOURITE: "merchant/getFavouriteList?",
  // GET_LASTORDER: 'order/pagination?',
  GET_LASTORDER: "order/orderListing?",

  GET_ALL_LISTING: "product/getMerchantBySubCat?",
  GET_MERCHANT_ITEMS: "product/pagination?",
  LIKE: "product/fav-unfav-product",
  GET_BANNERS: "banner/pagination?",
  ADD_CART: "cart/create",
  GET_CART: "cart/getCart",

  ADD_NEW_ADDRESS: "user/addAddress",
  GET_ADDRESS: "user/getAddressList",
  UPDATE_ADDRESS: "user/updateAddress",
  DELETE_ADDRESS: "user/deleteAddress",
  REMOVE_PRODUCT: "cart/deleteItem",
  UPLOAD_ID: "order/upload",
  MAKE_ORDER_REQUEST: "order/create",
  CLEAR_CART: "cart/deleteCart",
  ADD_CARD: "stripe/addCard",
  GET_CARD: "stripe/cardList",
  REMOVE_CARD: "stripe/deleteCard",
  GET_TAX: "payment-setting/tax",
  GET_USER: "user/findbyid?id=",
  GET_ADDON: "product/getProductAddOn/",
  GET_FAQ: "faq/pagination?page=1&pagesize=25",
  GET_NOTIFICATION: "notification/getUserNotiSetting",
  UPDATE_NOTIFICATION: "notification/updateUserNotiSettings",
  UPDATE_USER: "user/updateUserInfo",
  LOGOUT: "user/logout",
  SOCKET_REGISTER: "user/socketEvent",
  UPLOAD_CHAT_IMG: "order/upload",
  GET_CHAT_LISTING: "chat/getConversation",
  DELETE_CHAT: "chat/deleteChat",
  GET_INBOX: "chat/getInbox?",
  CREATE_CHAT_ROOM: "chat/createRoom",
  RATE_USER: "rating/rateDriver",
  CHECK_ZONE: "cart/checkZone",
  FETCH_ZONE: "cart/findZone",
  GET_TERMS: "page/getPage/",
  MAKE_CUSTOM_ORDER_REQUEST: "order/createCustomOrder",
  COMPLETE_JOB: "order/order-otp-verify",
  GET_ADMIN_ID: "chat/get-admin-id",
  UPDATE_ORDER_STATUS: "order/update-status",
  MUTE_CHAT: "chat/muteChat",
  READ_MESSAGES: "chat/readMessage",
  CHANGE_PASSWORD: "user/changepassword",
};
